services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: trading-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:16
    container_name: trading-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading
      POSTGRES_DB: trading
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: trading-redis
    ports:
      - "6379:6379"

  market-service:
    build:
      context: ../services/market
    container_name: trading-market
    ports:
      - "9000:9000"
    environment:
      REDIS_URL: redis://redis:6379/0
      MARKET_SYMBOL: BTCUSDT
      START_PRICE: 100.0
      SLEEP_SECONDS: 2
    depends_on:
      - redis

  order-service:
    build:
      context: ../services/order
    container_name: trading-order
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      ORDER_QUEUE: orders
      DATABASE_URL: postgresql://trading:trading@postgres:5432/trading
    depends_on:
      - rabbitmq
      - postgres

  execution-service:
    build:
      context: ../services/execution
    container_name: trading-execution
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      ORDER_QUEUE: orders
      DATABASE_URL: postgresql://trading:trading@postgres:5432/trading
      REDIS_URL: redis://redis:6379/0
      MARKET_SYMBOL: BTCUSDT
    depends_on:
      - rabbitmq
      - postgres
      - redis
      - market-service

volumes:
  pgdata: